### ISSUE TITLE
[markdown-it-mairmaid] Support passing options

### ISSUE THREAD

**Issue by mrleblanc101** [markslides/markslides#16]
Support passing any option, why are they hardcoded ?
ui-mono font display as serif on my Mac.
![Screenshot 2024-08-07 at 3 07 27 PM](https://github.com/user-attachments/assets/da05ce25-99b0-47ea-80c8-91b080cb8274)

**Comment by soaple** [comment]
Now, you can pass options to `markdownItMermaid()` function(`markdown-it-mermaid@^0.3.3`).
Try the new version and if it still doesn't work, open a new issue.

**Comment by mrleblanc101** [comment]
@soaple The plugin doesn't seem to work anymore when I update to `0.3.3`, reverting to `0.3.2` works.
No error shown on the browser console.
Currently investigating.

**Comment by mrleblanc101** [comment]
I think the refactor to return a method instead of a markdown-it instance doesn't work: 
https://github.com/markslides/markslides/blob/894eef30d133aa1ef3c55628580be1747769a167/packages/markdown-it-mermaid/src/index.ts#L28C5-L28C33

If I revert all the code in `3.3.3` except the `...config` spread, everything works again.

Also, `ui-monospace` is only supported in Safari, so the default value should probably be the supported `monospace` value instead.
https://caniuse.com/?search=ui-monospace
![Screenshot 2024-08-08 at 1 50 38 PM](https://github.com/user-attachments/assets/e6147d25-fca0-4d31-af19-c567ab5a7f95)

**Comment by soaple** [comment]
@mrleblanc101 As you mentioned, plugin is changed to function at `v0.3.3`.

Example code:

```js
import markdownItMermaid from '@markslides/markdown-it-mermaid';

markdownItMermaid({
  fontFamily: 'monospace',
});
```

Can you show your working code using `v0.3.3`?

And I will change default font to `monospace`.
Thank you for sharing this information 😀

**Comment by mrleblanc101** [comment]
This works in 0.3.2, but doesn't in 0.3.3. Doesn't matter if I pass a config or not.
```
markdownIt({ html: true })
        .use(MarkdownItMermaid)
```

**Comment by soaple** [comment]
Did you try like below?

```ts
markdownIt({ html: true })
        .use(MarkdownItMermaid())
```

**Comment by mrleblanc101** [comment]
Oh, I see.
Since it's now a function, I should call it like so:
```
markdownIt({ html: true })
        .use(MarkdownItMermaid())
```
But I'm pretty sure this is an error. No other markdown it plugin works like so.

**Comment by mrleblanc101** [comment]
But as I was saying originally. You can revert all change in 0.3.3, and only accept a second `config` argument to the constructor and spread it like you did. Not sure I understand the why you made those other changes.

```diff
import MarkdownIt from 'markdown-it';
import Token from 'markdown-it/lib/token';
import Renderer from 'markdown-it/lib/renderer';
import mermaid from 'mermaid';

const mermaidChart = (code: string) => {
    try {
        mermaid.parse(code, { suppressErrors: true });
        return `<div class="mermaid">${code}</div>`;
    } catch ({ str, hash }: any) {
        return `<pre>${str}</pre>`;
    }
};

// TODO: Inject this value from outside
const isDarkMode = false;

- const markdownItMermaid = (md: MarkdownIt) => {
+ const markdownItMermaid = (md: MarkdownIt, config) => {
    mermaid.initialize({
        theme: isDarkMode ? 'default' : 'dark',
        darkMode: isDarkMode,
        fontFamily: 'ui-monospace',
        altFontFamily: 'monospace',
        startOnLoad: true,
+        ...config
    });

    // @ts-ignore
    md.mermaid = mermaid;

    const original =
        md.renderer.rules.fence ||
        function (tokens, idx, options, env, self) {
            return self.renderToken(tokens, idx, options);
        };

    md.renderer.rules.fence = (
        tokens: Token[],
        idx: number,
        options: MarkdownIt.Options,
        env: any,
        self: Renderer
    ) => {
        const token = tokens[idx];
        const code = token.content.trim();
        if (token.info === 'mermaid') {
            return mermaidChart(code);
        }

        return original(tokens, idx, options, env, self);
    };
};

export default markdownItMermaid;
```

**Comment by mrleblanc101** [comment]
The config should be a second argument like so:
```
markdownIt({ html: true })
        .use(MarkdownItMermaid, {
            theme: 'default',
        })
```
And not a function param

**Comment by soaple** [comment]
@mrleblanc101 Thank you for your suggestion.
I wasn't familiar with markdown-it plugin, so I implemented it as a function call.
Currently, it was fixed like your suggestion at `v0.3.4`.
Check it out, and if you still have a problem please let me know😀

**Comment by mrleblanc101** [comment]
Yes 🙌 
And with your monospace fix, I might not even need the config param, but it's still great to have it !
I might try other themes to test how they look, couldn't find any picture in the mermaid doc so I have no idea how the 4 other themes look 👀

**Comment by soaple** [comment]
For your reference 😀

### `default`
<img width="372" alt="image" src="https://github.com/user-attachments/assets/6c9d9c07-e9d1-4862-a78e-d17a03396259">

### `neutral`
<img width="382" alt="image" src="https://github.com/user-attachments/assets/a4dda6c4-059f-46a5-8931-effaeda14180">

### `dark`
<img width="367" alt="image" src="https://github.com/user-attachments/assets/92e78fac-31c7-48d6-a25a-8f74bfabb597">

### `forest`
<img width="365" alt="image" src="https://github.com/user-attachments/assets/402936b1-93cd-4508-b578-6b6fa3b8dc44">

### `base`
<img width="366" alt="image" src="https://github.com/user-attachments/assets/dbe2b961-26ef-451a-ae23-8c2adedc5e9f">

**Comment by mrleblanc101** [comment]
@soaple 
I've just realized that my charts were not working anymore after updating.
Seems like `theme` is now mandatory, but ommiting it doesn't fallback to a default value and it doesn't crash either.
It only render the raw code instead of the mermaid chart.

This doesn't work:
```
.use(MarkdownItMermaid)
```
This works:
```
.use(MarkdownItMermaid, {
    theme: 'neutral',
})
```

**Comment by inje-lee** [comment]
@mrleblanc101 Thank you for your comment.

You need to pass the config(even empty) like below:
```js
marp.use(markdownItMermaid, {});
```
I'll make the `config` optional in the next update.

---

Also, is your flowchart syntax correct?
It didn’t work on my machine.
However, the following syntax worked well:
```
flowchart TD
    BE[Back-end] --> PHP[PHP]
    PHP --> L[Laravel]
    PHP --> CP[CMS]
    L --> LN[Laravel Nova]
    L --> PI[Filament]
    CP --> T[TYPO3]
    CP --> W[WordPress]
    CP --> D[Drupal]
```
Could you please check your code?

**Comment by soaple** [comment]
@mrleblanc101  Thank you for your comment.

You need to pass the config(even empty) like below:
```js
marp.use(markdownItMermaid, {});
```
I'll make the `config` optional in the next update.

---

Also, is your flowchart syntax correct?
It didn’t work on my machine.
However, the following syntax worked well:
```
flowchart TD
    BE[Back-end] --> PHP[PHP]
    PHP --> L[Laravel]
    PHP --> CP[CMS]
    L --> LN[Laravel Nova]
    L --> PI[Filament]
    CP --> T[TYPO3]
    CP --> W[WordPress]
    CP --> D[Drupal]
```
Could you please check your code?

**Comment by mrleblanc101** [comment]
> You need to pass the config(even empty) like below

Yeah, I've just specified the theme manually, no worry.

> I'll make the config optional in the next update.

That would be a great improvement

> Also, is your flowchart syntax correct?

Nah, the mermaid codeblock is correctly formatted. 
My screenshot shows the rendered output which doesn't have a `<pre>`, so everything is on one line when `markdown-it-mermaid` doesn't render the chart (because of the omited option object).
